[package]
name = "polymenu"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
clap = { version = "4.5.40", features = ["derive"] }
csv = "1.3.1"
fuzzy-matcher = "0.3.7"
polymenu-derive = { path = "../derive" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
tracing-subscriber = "0.3.19"
winit = "0.30.11"
winit-gtk = "0.29.1"
wry = { version = "0.52.1", features = ["transparent"] }
