# Specify to read items from a file instead of stdin
# file = "path/to/your/file"

# Specify what format the input will come in
# format = "csv"

# If format is headless_csv, specify the column names
# columns = ["key", "value"]

file = "gallery/fuzzy-finder/countries.json"
app_src = "gallery/fuzzy-finder"

[window]
width = 1050
height = 2000

# Define options specific to this app that can be overriden at runtime
[options]
# Prompt to be displayed as a placeholder in the text input box
prompt = ""

# Initial value for the text input box
query = ""

# How to treat case-sensitivity
case = "smart"


# Define CLI commands that you can call from inside your app
[commands.say_hello]
command = ["echo", "hello"]

[commands.say_anything]
# output_format = "raw" # Parse the output of your command. json, jsonlines, csv, headless_csv (defaults to raw)
command = [
  "echo",
  "$message", # Use `$argument_name` to reference arguments that you will pass from your app 
]
