# Specify to read items from a file instead of stdin
# file = "path/to/your/file"

# Specify what format the input will come in
# format = "csv"

# If format is headless_csv, specify the column names
# columns = ["key", "value"]

file = "gallery/fuzzy-finder/countries.json"
src = "gallery/fuzzy-finder"

[window]
width = 1050
height = 2000

# Define app-specific options that can be overriden at runtime
[options]
placeholder = "Find a country"
case_sensitive = false

# Define CLI commands that you can call from inside your app
[commands.say_hello]
command = ["echo", "hello"]

[commands.say_anything]
# output_format = "raw" # Parse the output of your command. json, jsonlines, csv, headless_csv (defaults to raw)
command = [
  "echo",
  "$message", # Use `$argument_name` to reference arguments that you will pass from your app 
]
